### ISSUE TITLE
Stacked Plus Ordered Is Not as Expected

### ISSUE THREAD

**Issue by msalamon1** [emmerich/flot-orderBars#5] opened 2015-01-18 00:28 UTC
I was searching for a way to get both stacked and ordered bar charts using Flot and I had hoped this was the answer.  However, at least based on your example, it does not work the way that most stacked and ordered bar charts work.

See the question I posted here:  http://stackoverflow.com/questions/27726417/multi-dimensional-stacked-bar-chart-with-zingchart about ZingCharts and the answer that was provided. The answer shows how it should look.  As you can see, every bar chart in that example has the same series of data.  There is a red, yellow, blue and green component to every bar, because you are examining the same series of data across both the xaxis dimension and the extra dimension.

In your example, each bar per X axis tick holds different data. Order 0/Stack 1, holds the data for series 1 and 2 and Order 1/Stack 2 holds the data for series 3 and 4.

Any idea how to get this to work the way that I was hoping?

**Comment by emmerich** [comment] 2015-01-19 10:09
So I'm clear, is the issue that the format you supply the data to the orderBars plugin is different to ZingCharts? Haven't had time to look into the details of the data format (it could be that I'm doing it wrong), but in the mean time is it possible to apply a transform to your data before you pass it to orderBars?

**Comment by msalamon1** [comment] 2015-01-19 13:39
To be honest, I'm not exactly sure.  :)  The issue is that the output is not what is typically expected in a stacked + ordered bar chart.  You want every stack to include the same series of data, as I explained.  Whether you get that by changing the data format, how the underlying plugin works, or something else, I don't know. I tried it where I had the 4 series of data but I gave one in each order the same label, but that had no effect.  For ex, Series 1 was "East" + Order 0, Series 2 was "West" + Order 0, Series 3 was "East" + Order 1 and Series 4 was "West" + Order 1. I thought it might automatically combine them together, but it did not.  If there is a data format that will make this work, let me know, but I suspect that the plugin needs to be changed to accommodate this.

Any help you can provide would be great.

**Comment by emmerich** [comment] 2015-01-19 14:28
In your example wouldn't East Order 0,  West Order 1, East Order 0, West Order 1 work?

I think what I'm struggling to understand is that in the StackOverflow question you supplied, the output of the Chart looks the same semantically as the examples of orderBars (unless I missed something?). The only difference is in the way the data is provided to the libraries. Or is there something semantically different about the charts?

**Comment by msalamon1** [comment] 2015-01-19 14:45
In your example, you had 4 different series of data.  They weren't labeled, so I can't reference them by label.  But for sake of argument, let's say they were A (order 0), B (order 0), C (order 1) and D (order 1).  The x-axis was just 0, 1 and 2.  In your solution, it looked like this:

B D    B D    B D
A C    A C    A C
 0         1        2

Even if I provide labels to these series and rename C to A and rename D to B, when I end up with this, which is CLOSE to what I want:

B B    B B    B B
A A    A A    A A
 0         1        2

The Order 1 bars have different colors than the Order 0 bars, and in the legend they are treated a 4 different series, not 2.  If I want to do anything with them, say toggle a certain series, they are treated as 4 series, not 2.  In this case, I want the chart to recognize that there are only 2 series of data for all purposes (colors, legend, etc.)

If you look at the zingcharts example, in every bar, you have the same series repeating over and over, with the same colors.

**Comment by emmerich** [comment] 2015-01-19 15:12
Starting to understand a bit better now..

The problem is that there's no way of splitting up a Series into multiple orders. You define 1 order for a Series and every X value in that Series has the same order. What you want to do is actually split a Series up into multiple orders. In the ZingCharts example, each "red" series has 3 bars at each x point, indicating it has been split up into 3 orders.

Having said that, the functionality you describe is not supported by ZingCharts either. If you look at the answer provided, they have split the red series into 3 individual series, one for each "stack". (Look for North 1, North 2 and North 3). Look at the legend-name for each North series, you'll see that each one has a different Legend name but North 2 and North 3 are hidden in the legend. I think if you tried to hide a Series in ZingCharts you'd get the same problem as you described.

My suggestion would be the same as the ZingCharts answer, which is to split up your data before you give it to flot. The downside is as you say you're dealing with multiple series, and will have to handle it in your series selection code. There will be ways to make this painless, but it'd be in your code outside of the library. Check out the composite pattern - your code will think it's calling methods on one Series but actually it's calling on multiple underneath. That's the cleanest way I think you can fix this.

**Comment by msalamon1** [comment] 2015-01-19 15:23
Interesting.  Thanks.  I can try to add code so that in all places the user experiences it as if they were the same series (colors, legends, toggle, etc.).  Would be great, obviously, if this could be done out of the box with one of the plugins. Thanks for your time and analysis.

**Comment by emmerich** [comment] 2015-01-19 15:26
No problem. It's something that I would raise as a new feature or improvement but as I'm not actively developing this project I'm going to close the issue.

**Closed by emmerich** 2015-01-19 15:26 UTC
